.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH HAYATE-SEND 1 "2026-07-04" "hayate 6.0.0" "Hayate Manual"
.SH NAME
send \- Send a file or directory to a receiver
.SH SYNOPSIS
\fBsend\fR [\fB\-\-code\fR] [\fB\-z\fR|\fB\-\-compress\fR] [\fB\-\-hash\fR]
[\fB\-\-no\-progress\fR] [\fB\-h\fR|\fB\-\-help\fR] <\fIPATH\fR> [\fITARGET\fR]
.SH DESCRIPTION
Send a file or directory to a receiver
.SH OPTIONS
.TP
\fB\-\-code\fR \fI<CODE>\fR
Cryptographic code\-phrase for pairing
.TP
\fB\-z\fR, \fB\-\-compress\fR \fI<COMPRESS>\fR [default: true]
Compress chunks with zstd level 1 before encrypting

\fIPossible values:\fR
.RS 14
.IP \(bu 2
true
.IP \(bu 2
false
.RE
.TP
\fB\-\-hash\fR \fI<HASH>\fR [default: blake3]
Hash algorithm for payload integrity (blake3, sha256)
.TP
\fB\-\-no\-progress\fR
Suppress the progress bar
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIPATH\fR>
Path to the file or directory to send
.TP
[\fITARGET\fR]
Receiver address in the form `ip:port` or `hostname:port`
