.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH man 1  "man " 
.SH NAME
man \- Generate man pages for the CLI
.SH SYNOPSIS
\fBman\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIOUT_DIR\fR] 
.SH DESCRIPTION
Generate man pages for the CLI
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIOUT_DIR\fR] [default: man]
Directory to write generated man pages into
