[package]
name = "hayate-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "High-performance command-line utility for direct LAN file transfer."
documentation = "https://shiinasaku.github.io/Hayate"
readme = "../README.md"
keywords = ["quic", "transfer", "cli", "lan", "utility"]
categories = ["command-line-utilities", "network-programming"]
publish = false

[package.metadata.dist]
dist = true

[lints]
workspace = true

[[bin]]
name = "hayate"
path = "src/main.rs"

[dependencies]
hayate = { path = "../hayate", version = "5.1.0" }
anyhow = { workspace = true }
clap = { workspace = true }
compio = { workspace = true }
compio-quic = { workspace = true }
console = { workspace = true }
inquire = { workspace = true }
flume = { workspace = true }
futures-util = { workspace = true }
indicatif = { workspace = true }
rand = { workspace = true }
