[package]
name = "hayate-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "High-performance command-line utility for direct LAN file transfer."
documentation = "https://docs.rs/hayate-cli"
readme = "../README.md"
keywords = ["quic", "transfer", "cli", "lan", "utility"]
categories = ["command-line-utilities", "network-programming"]
publish = false

[[bin]]
name = "hayate"
path = "src/main.rs"

[dependencies]
hayate = { path = "../hayate-engine", version = "3.0.0" }
anyhow = { workspace = true }
clap = { version = "4", features = ["color", "derive", "env"] }
compio = { workspace = true }
compio-quic = { workspace = true }
console = "0.16"
dialoguer = { workspace = true }
flume = "0.12.0"
futures-util = { workspace = true }
indicatif = { version = "0.18", features = ["improved_unicode"] }
rand = { workspace = true }
