[package]
name = "hayate-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "High-performance command-line utility for direct LAN file transfer."
documentation = "https://shiinasaku.github.io/Hayate"
readme = "../README.md"
keywords = ["quic", "transfer", "cli", "lan", "utility"]
categories = ["command-line-utilities", "network-programming"]
publish = false

[package.metadata.dist]
dist = true

[package.metadata.wix]
upgrade-guid = "6DF64A3F-ED31-405A-A678-5515B5E6BDC5"
path-guid = "31978D25-8C07-41E3-994C-62AE441D1918"
license = false
eula = false

[lints]
workspace = true

[[bin]]
name = "hayate"
path = "src/main.rs"

[dependencies]
hayate = { path = "../hayate", version = "5.1.1" }
anyhow = { workspace = true }
clap = { workspace = true }
compio = { workspace = true }
compio-quic = { workspace = true }
console = { workspace = true }
flume = { workspace = true }
futures-util = { workspace = true }
if-addrs = { workspace = true }
indicatif = { workspace = true }
inquire = { workspace = true }
crossterm = { version = "0.29", default-features = false, features = ["events"] }
rand = { workspace = true }
